### ISSUE TITLE
Error: "journal-categories.valueSet" is not a registered game setting

### ISSUE THREAD

**Issue by qw3ry** [Muwak77/journal-backlinks-extended#3]
Some backlinks are displayed, others are not. In the console I can see the following error:
```
Fehler beim Abrufen von werteText aus den Einstellungen: Error: "journal-categories.valueSet" is not a registered game setting
    #assertKey /scripts/foundry.js:3402
    get /scripts/foundry.js:3334
    includeLinks /modules/journal-backlinks-extended/scripts/journallink.js:238
    includeJournalPageLinks /modules/journal-backlinks-extended/scripts/journallink.js:204
    #call /scripts/foundry.js:632
    callAll /scripts/foundry.js:589
    _callHooks /scripts/foundry.js:5918
    _renderPageViews /scripts/foundry.js:78665
    _render /scripts/foundry.js:78629
    render /scripts/foundry.js:5793
    _onClickEntryName /scripts/foundry.js:73976
    jQuery 8
    activateListeners /scripts/foundry.js:73165
    activateListeners /scripts/foundry.js:73964
    _render /scripts/foundry.js:5867
    _render /scripts/foundry.js:72780
    _render /scripts/foundry.js:73125
    _render /scripts/foundry.js:73922
    _render /scripts/foundry.js:74626
    render /scripts/foundry.js:5793
    initializeUI /scripts/foundry.js:9245
    setupGame /scripts/foundry.js:9083
    _initializeGameView /scripts/foundry.js:10432
    _initializeView /scripts/foundry.js:10408
    initialize /scripts/foundry.js:8995
    async* /scripts/foundry.js:95974
    async* /scripts/foundry.js:95954
```
This occurs on a native v12 world (not migrated from v11). I am using other plugins, but I disabled them all for testing this issue. They might cause data problems, though.

Edit: Since the module is verified v12 this does not seem to be a general v12 issue? I think I confused this when writing the issue with the older backlink plugins

Edit2: I noticed that in some cases, the backlinks work, but in others, they don't. Rebuilding does not help. So this might be a data issue caused by other plugins. Above error does still occur, though, and looks somewhat suspicious to me.

**Comment by qw3ry** [comment]
I tested more and created a new world with only this module enabled. There the backlinks seem to work fine, so I guess my issue is related to the data.

Still, it would be nice to have that warning gone, so I am keeping this issue open - you may close it as you wish.

**Comment by itaags8** [comment]
i See the issue is related to journal Categories which works in Conjunction with the backlink-module. I'll fix this with the next update

**Comment by Muwak77** [comment]
i See the issue is related to journal Categories which works in Conjunction with the backlink-module. I'll fix this with the next update
