### ISSUE TITLE
name of the original journal entry not in the backlink

### ISSUE THREAD

**Issue by cnschu** [Muwak77/journal-backlinks-extended#4]
## shown behavior
If i link from a page of a journal entry to another journal entry, the generated backlinks show only the name of the page, no hint in wich journal entry the page is (see screenshot).
![grafik](https://github.com/user-attachments/assets/af0e2ff5-0c09-42ac-96be-efd6cbebbf0b)

## expected behavior
Display the name of the journal entry in the backlink.
OR
Have an option to configure, what should be shown in the backlink (Journal Entry, Page, or both).

Thanks a lot in advance, love the extension.

**Comment by Muwak77** [comment]
Good Point, will bei done with the next Update

**Comment by Muwak77** [comment]
You can test in with by installing the new alpha

https://github.com/Muwak77/journal-backlinks-extended/releases/download/0-12-6a/module.json
