### ISSUE TITLE
Link List not visible in the table of contents of the target journal entry

### ISSUE THREAD

**Issue by cnschu** [Muwak77/journal-backlinks-extended#5]
## seen behavior
The link-list is not visible in the table of contents of the journal entry.
(see screenshot)
![grafik](https://github.com/user-attachments/assets/52477b7c-0619-4095-9f71-1c61be78ba23)

## expected behavior
The Link List should be visible in the table of contents according to the selectes "h" tag (h1 = page, h2 below page and so on).

Thanks a lot in advance.

**Comment by Muwak77** [comment]
That's currently not intended, as it would create the same heading for every page. But I'll consinder it as an optional Setting für the next Update. Thanks for the Idea.

**Comment by cnschu** [comment]
yeah you are right.

i was under the misconception, that the links refer to the journal entry, not the journal page.
displaying the "linked from" heading for every single page in the TOC would be stupid. So just drop the idea :)

**Comment by Muwak77** [comment]
To late:) I Found it pretry useful for long pages and it does not hurt so i added it as a new Feature für the upcoming version 

You can test in with by installing the new alpha

https://github.com/Muwak77/journal-backlinks-extended/releases/download/0-12-6a/module.json
